# Generated by Django 4.0.1 on 2022-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_info',
            name='category_name',
            field=models.CharField(choices=[('IT', 'IT')], max_length=200),
        ),
    ]
